title: Cybertorii's Projects
description: Passionate programming student, I want to share my passion through many projects.\ As a mad scientist said, human is a temporal being.
show_downloads: true
theme: jekyll-theme-hacker
